# Generated by Django 3.2.16 on 2024-06-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20240628_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='image',
        ),
    ]
