# Generated by Django 3.2.16 on 2024-06-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_remove_birthday_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='birthday',
            name='Unique person constraint',
        ),
        migrations.AddField(
            model_name='birthday',
            name='image',
            field=models.ImageField(blank=True, upload_to='birthdays_images', verbose_name='Фото'),
        ),
    ]
